[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Online store of rocks, using the DeDe application, which is a decentralized application for online purchase of products. 
The application will simulate the basic functionalities of an online store, where users and clients can buy different types of rocks.
****

=== Requirements Overview

[role="arc42help"]
****
The application will be online and accessible from anywhere in the world. Users will be able to search in the catalog any product available in our shop. 
The users can order different items and the price will be calculated depending on the place from where the order is made and the products that the client buys.
The application will store the information about the users and the products in a database MongoDB. Personal information of the users will be protected with SOLID using pods.
The application interfaces will be created with an open source library React and the main language for the application will be TypeScript.
	


****

=== Quality Goals

[role="arc42help"]
****
[options="header",cols="1,2,2"]
|===
|Priority|Quality|Motivation
| 1 | Privacy | The user must know that his personal information is protected using our application.
| 2 | Modifiability | The technology is constantly changing and is essential to keep up to date.
| 3 | Efficiently | The application functionalities should be efficient for the users.
| 4 | Usability | The application must be adapted for every type of user.
|===
****

=== Stakeholders

[role="arc42help"]
****
[options="header",cols="1,2,2"]
|===
|Role|Expectations| 
| Teachers | Implementation that shows the knowledges of the lessons |
| Server admin | Server gestion and solve technical problems and doubts |
| Clients | Application easy to manage with a clear interface and adapted to all levels of software knowledge |
|===
****


